baseurl = "https://yasuomatsuoka.github.io/blog/"
languageCode = "ja"
title = "やすおのぶろぐ"
theme = "ghostwriter"
canonifyurls = true # 相対パスではなく baseurl を基点とした絶対パスにする
googleAnalytics = "UA-77379841-1"
copyright = "Yasuo Matsuoka"

[Author]
  name = "Yasuo Matsuoka"

[params]
  intro = true
  headline = "やすおのぶろぐ"
  description = "ソフトウェア開発の備忘録や自転車や食べ物のこと"
  twitter = "https://twitter.com/yasuomatsuoka"
  github = "https://github.com/yasuomatsuoka"
  linkedin = "https://linkedin.com/in/XXX/"
  profile = "/images/profile.jpg"
  opengraph = true

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/:year/:month/:title/"
